
#targets += sgvar.lua vmap.lua e2ibus.lua e2sbus.lua e2xjt.lua vsp.lua schotl.lua comp.lua increm.lua test.lua
targets += sgvar.lua vmap.lua vsp.lua schtl.lua incrm.lua test.lua

sgvar.lua: sgvar.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

vmap.lua: vmap.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

incrm.lua: incrm.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

schtl.lua: schtl.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

vsp.lua: vsp.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

#e2ibus.lua: e2ibus.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

#e2sbus.lua: e2sbus.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

#e2xjt.lua: e2xjt.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

#comp.lua: comp.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

test.lua: test.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

-include ../../makefile.include
