targets += tiny.lua medium.lua large.lua

large.lua: large.lpp ../../global.h ../../version.h ../../constants.h 

medium.lua: medium.lpp ../../global.h ../../version.h ../../constants.h 

tiny.lua: tiny.lpp ../../global.h ../../version.h ../../constants.h 

subdirs = SLIDER

-include ../../makefile.include
