targets += tiny.lua medium.lua large.lua tiptip.lua

large.lua: large.lpp ../../global.h ../../version.h ../../constants.h 

medium.lua: medium.lpp ../../global.h ../../version.h ../../constants.h 

tiny.lua: tiny.lpp ../../global.h ../../version.h ../../constants.h 

tiptip.lua: tiptip.lpp ../../global.h ../../version.h ../../constants.h 

subdirs = SLIDER REMOTE

-include ../../makefile.include
