targets += libA.lua libI.lua libD.lua libP.lua

 libA.lua: libA.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

libD.lua: libD.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

libI.lua: libI.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

libP.lua: libP.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

-include ../../makefile.include
