targets += libA.lua libI.lua libD.lua libP.lua libU.lua libM.lua libR.lua

libA.lua: libA.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh sort.lh

libD.lua: libD.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

libI.lua: libI.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh libconfig.lh

libM.lua: libM.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh libconfig.lh

libP.lua: libP.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh sort.lh

libU.lua: libU.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

libR.lua: libR.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

-include ../../makefile.include
