
targets += wmsw2.lua wms2c.lua
	
wmsw2.lua: wmsw2.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

wms2c.lua: wms2c.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

-include ../../makefile.include
