
targets += wmsw2.lua wms2c.lua wm2adr.lua wm2ani.lua
	
wmsw2.lua: wmsw2.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

wms2c.lua: wms2c.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

wm2adr.lua: wm2adr.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

wm2ani.lua: wm2ani.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

-include ../../makefile.include
