targets += tiny.lua medium.lua large.lua Demo1.lua
targets += da5.lua most.lua da6.lua da16.lua
targets += tiptip.lua
targets += virt.lua areset.lua
targets += tiny.lua.extract tiny.lua.html

subdirs = LSBUT

-include ../../makefile.include
