targets += default.lua horiz.lua

default.lua: default.lpp ../../../global.h ../../../version.h ../../../constants.h 

horiz.lua: horiz.lpp ../../../global.h ../../../version.h ../../../constants.h 

-include ../../../makefile.include
