targets += wmcompile.lua test01.lua wmversion.lua adrchange.lua

wmcompile.lua: wmcompile.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

adrchange.lua: adrchange.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

test01.lua: test01.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

wmversion.lua: wmversion.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

-include ../../makefile.include
