targets += wmcompile.lua test01.lua

wmcompile.lua: wmcompile.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

test01.lua: test01.lpp ../../global.h ../../version.h ../../constants.h ../../functions.lh

-include ../../makefile.include
